name: persistent_bottom_nav_bar_v2_example_project
description: An example project for persistent_bottom_nav_bar_v2

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  persistent_bottom_nav_bar_v2:
    path: ../

flutter:
  uses-material-design: true
