name: persistent_bottom_nav_bar_v2
description: A highly customizable bottom navigation bar for Flutter. It is shipped with 17 prebuilt styles you can choose from, but can also be used with your very own style without sacrificing any features. Based on persistent_bottom_nav_bar which currently is not continued.

homepage: https://github.com/jb3rndt/PersistentBottomNavBarV2
repository: https://github.com/jb3rndt/PersistentBottomNavBarV2
version: 5.0.0-beta.6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

cider:
  link_template:
    tag: https://github.com/jb3rndt/PersistentBottomNavBarV2/releases/tag/%tag% # initial release link template
    diff: https://github.com/jb3rndt/PersistentBottomNavBarV2/compare/%from%...%to% # subsequent releases link template
